### ISSUE TITLE
Add documentation for retaining properties with geo2topo

### ISSUE THREAD

**Issue by omundy** [topojson/topojson-server#1]
Before the name change from ```topojson``` to ```geo2topo``` (per many [threads](http://stackoverflow.com/questions/18444261/how-to-add-properties-to-topojson-file) on [stackoverflow](http://stackoverflow.com/questions/14095316/topojson-properties-preservation))  it was possible to retain properties from the original geojson file with the following 

`topojson in.json -o out.json -p prop1,prop2`

Can geo2topo still do this? It would be great if the documentation covered this.

**Comment by mbostock** [comment]
Any properties and identifiers of input [feature objects](https://tools.ietf.org/html/rfc7946#section-3.2) are propagated to the output. If you want to transform or filter properties, try [ndjson-cli](https://github.com/mbostock/ndjson-cli) as demonstrated in [Command-Line Cartography](https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c).

**Comment by woodz-** [comment]
Is there a test for this?
#14
