### ISSUE TITLE
customized top level properties are thrown out

### ISSUE THREAD

**Issue by woodz-** [topojson/topojson-server#14]
**notes**
1. working without pipes but file based - input is the resulting output file from the previous converting step
2. issue is even valid for **`geostitch`**

**tooling and versions**
├── d3-geo-projection@2.4.0
├── ndjson-cli@0.3.1
├── npm@3.10.10
├── plugman@1.4.1
├── shapefile@0.6.6
├── topojson-server@3.0.0
└── topojson-simplify@3.0.2
`$ node --version: v6.11.2`

**reproduce**
1. using "ne_10m_admin_0_countries.shp" from unzipped [natural earth](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip)
2. `$ shp2json -n "./ne_10m_admin_0_countries.shp" > "ne_10m_admin_0_countries-ndjson.geojson"`
3. `$ ndjson-map 'i = d.properties.ISO_A3, d.iso = i === "-99" ? undefined : i, i = d.properties.NAME_LONG, d.name = i === "-99" ? undefined : i, delete d.properties, d' < "ne_10m_admin_0_countries-ndjson.geojson" > "ne_10m_admin_0_countries_country_codes.json"`
4. `$ geo2topo -q 1e5 -n countries="./ne_10m_admin_0_countries_country_codes.json" > "./ne_10m_admin_0_countries.topojson"`

if you then look into "ne_10m_admin_0_countries.topojson", you should see the properties `"iso"` and `"name"` are gone, against many tutorials on the internet like this: [medium](https://medium.com/@aendrew/creating-topojson-using-d3-v4-10838d1a9538), while they are in "ne_10m_admin_0_countries_country_codes.json"

could anybody confirm and maybe explain why this is happening?

here is a rather old [sof discussion](https://stackoverflow.com/questions/14095316/topojson-properties-preservation)

**Comment by mbostock** [comment]
This is the expected behavior. If you want features with properties, you need to put them on a properties object, as defined in the [GeoJSON specification, section 3.2](https://tools.ietf.org/html/rfc7946#section-3.2). `geo2topo` does not propagate unknown fields.

**Comment by woodz-** [comment]
That makes sense, thank you for the tip @mbostock
For me it's still misleading while I am referencing to your [world-atlas](https://github.com/topojson/world-atlas/blob/master/prepublish). For my understanding, the `properties` object is not explicitly generated in the topojson output and your clever established `d.id` on the geojson's root will be gone like in my approach above.
Do you confirm or di I miss somthing here?
Anyways, my intent is to create a pull request and link it to here. You are welcome to reject it if I should have misunderstood the whole thing.

**Comment by woodz-** [comment]
link to pull request to the [world-atlas](https://github.com/topojson/world-atlas/blob/master/prepublish) repo: [ensure custom properties propagation](https://github.com/topojson/world-atlas/pull/22)

**Comment by mbostock** [comment]
The world-atlas doesn’t include any properties. It only includes a unique identifier.
