### ISSUE TITLE
Documentation refers to a mystery us-states.json GeoJSON file

### ISSUE THREAD

**Issue by mvl22** [topojson/topojson-server#7]
The README refers to a `us-states.json` file, but there does not seem to be any such file in the repo, nor any  link to where it is (if it is intended to be from some other location).

As such, it is harder than ideal for a new user to figure out how the library works and be sure what kind of expected data is required by way of example.

**Comment by mbostock** [comment]
That’s not referring to a specific file, but the *idea* of a file containing a GeoJSON object. If you want a more concrete example, I would recommend reading [Command-Line Cartography](https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c).
